# Generated by Django 3.2.8 on 2021-12-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kittalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='images\\shelters')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kittalog.shelter'),
        ),
    ]
